### ISSUE TITLE
THE TUTORIAL LINK OPENS UP A 404 NOT FOUND ERROR

### ISSUE THREAD

**Issue by BlessingD** [MobileFirst-Platform-Developer-Center/OfflineAuthentication#1]
Hi, I really would like to use this library,however, the link to the tutorial opens up a 404 not found error page.

**Comment by sreelathasankaranarayanan** [comment]
The link to the tutorials is outdated. Please use the updated link below
https://mobilefirstplatform.ibmcloud.com/tutorials/en/foundation/7.1/advanced-topics/offline-authentication/

**Comment by sreelathasankaranarayanan** [comment]
Please close the Git issue if your issue is addressed. Thanks.

**Comment by BlessingD** [comment]
thanks a lot for the link.
